name: 'Update Java Dependencies'
description: 'Met à jour les dépendances Java et les JARs'
inputs:
  update_type:
    description: 'Type de mise à jour (release ou snapshot)'
    required: true
    default: 'release'
    type: string
  branch:
    description: 'Branche sur laquelle appliquer les changements'
    required: false
    default: 'develop'
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        ref: ${{ inputs.branch }}
        fetch-depth: 0

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - uses: s4u/setup-maven-action@v1.20.0
      with:
        checkout-enabled: false

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: List updated dependencies
      if: inputs.update_type == 'release'
      id: get-updated-deps
      shell: bash
      run: |
        MVN_OUTPUT=$(mvn versions:update-properties -DallowDowngrade)

        # Générer le message
        UPDATED_DEPS=$(echo "$MVN_OUTPUT" | sed -n 's/.*Updated ${\([^}]*\)\.version} from \([^ ]*\) to \([^ ]*\).*/Updated \1 JARS from \2 to \3/p')

        echo "Updated dependencies:"
        echo "$UPDATED_DEPS"
        echo "updated_deps=$UPDATED_DEPS" >> $GITHUB_OUTPUT

    - name: Update release dependencies
      if: inputs.update_type == 'release'
      shell: bash
      run: mvn versions:update-properties -DallowDowngrade

    - name: Update snapshot dependencies
      if: inputs.update_type == 'snapshot'
      shell: bash
      run: mvn versions:update-properties -DallowSnapshots -DallowDowngrade

    - name: Copy jars
      shell: bash
      run: mvn -Pcopy-jars

    - name: Update NEWS.md with all dependencies
      if: inputs.update_type == 'release'
      shell: bash
      env:
        UPDATED_DEPS: ${{ steps.get-updated-deps.outputs.updated_deps }}
      run: |
        if [ -z "$UPDATED_DEPS" ]; then
          echo "No updates detected."
        else
          # Call heylogs for each updates
          echo "$UPDATED_DEPS" | while IFS= read -r line; do
            mvn -U com.github.nbbrd.heylogs:heylogs-maven-plugin::push \
              -Dheylogs.inputFile=NEWS.md \
              -Dheylogs.type=changed \
              -Dheylogs.message="$line"
          done
        fi

    - name: Commit changes
      shell: bash
      run: |
        git add -A
        if git diff --cached --quiet; then
          echo "No change detected"
          exit 0
        fi
        git commit \
          -m "Update Java dependencies (${{ inputs.update_type }})" \
          -m "Co-authored-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"

    - name: Push changes
      shell: bash
      run: git push origin ${{ inputs.branch }}
